### ISSUE TITLE
Create Designs

### ISSUE THREAD

**Issue by Tumne** [kammanz/raptors-app#2]
These are the list of designs that need to be implemented. This ticket will stay open as an Epic ticket:

- [x] Navigation top bar #3
- [x] List of players (should be like tiled playing cards) #9 
- [x] Hover/Selected player state #9
- [x] Placeholder for photo #9
- [x] Placeholder for details #14
- [x] Loading states (list, details) #13 
- [x] Details of player (stats, photo, game stats)  #10
- [x] Filter players (year, position, stats) #11
- [x] Search filter  (by first and last name) #12
