### ISSUE TITLE
Deploy Version 1.0

### ISSUE THREAD

**Issue by kammanz** [kammanz/raptors-app#6]
ETA: `3 days`
---

Epic task:

- [x] Secure domain name #106 
- [x] Secure/setup hosting #117 
- [x] Create production ready code #118 
- [x] Deploy to digital ocean #119
